{% set name = "djangorestframework-filters" %}
{% set version = "1.0.0.dev0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: ef84527e3427434d54228825b53a35098c8633c1e77b71d06b79597b749ea3f2

build:
  noarch: python
  number: 1
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.4
  run:
    - django-filter >=2.0
    - djangorestframework
    - python >=3.4

test:
  imports:
    - rest_framework_filters
    - rest_framework_filters.templatetags

about:
  home: http://github.com/philipn/django-rest-framework-filters
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: "Better filtering for Django REST Framework"
  dev_url: http://github.com/philipn/django-rest-framework-filters

extra:
  recipe-maintainers:
    - mxr-conda
